//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CCLM.ORM
{
    using System;
    using System.Collections.Generic;
    
    public partial class distribution_centers
    {
        public distribution_centers()
        {
            this.users = new HashSet<users>();
        }
    
        public int id { get; set; }
        public Nullable<int> code { get; set; }
        public string name { get; set; }
        public Nullable<System.TimeSpan> process_start_time { get; set; }
        public Nullable<System.TimeSpan> process_end_time { get; set; }
        public Nullable<int> binnacle_days { get; set; }
        public Nullable<bool> mail_success { get; set; }
    
        public virtual ICollection<users> users { get; set; }
    }
}
