//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CCLM.ORM
{
    using System;
    using System.Collections.Generic;
    
    public partial class users
    {
        public users()
        {
            this.distribution_centers = new HashSet<distribution_centers>();
        }
    
        public int id { get; set; }
        public string nickname { get; set; }
        public string full_name { get; set; }
        public string email { get; set; }
        public Nullable<bool> is_full { get; set; }
    
        public virtual ICollection<distribution_centers> distribution_centers { get; set; }
    }
}
